schema_compatibility: Get the current cron.database_name settings
Fixed:

ERROR:  can only create extension in database postgres
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'sms' in postgresql.conf to use the current database.